# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$python\
$job\
$line_break\
$character\
"""

# palette = "nord"

# Drop ugly default prompt characters
[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[fill]
symbol = " "

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# ---y

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '󰋜 ~/'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
style = "bold yellow"

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'


# [palettes.nord]
# dark_blue = '#5E81AC'
# blue = '#81A1C1'
# teal = '#88C0D0'
# red = '#BF616A'
# orange = '#D08770'
# green = '#A3BE8C'
# yellow = '#EBCB8B'
# purple = '#B48EAD'
# gray = '#434C5E'
# black = '#2E3440'
# white='#D8DEE9'

# [palettes.onedark]
# dark_blue='#61afef'
# blue='#56b6c2'
# red='#e06c75'
# green='#98c379'
# purple='#c678dd'
# cyan='#56b6c2'
# orange='#be5046'
# yellow='#e5c07b'
# gray='#828997'
# white ='#abb2bf'
# black='#2c323c'

# Shows current git branch
[git_branch]
symbol = ' '
format = '[on](white) [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '


# ---


[python]

format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
style = "bold teal"
pyenv_version_name = false
pyenv_prefix = "pyenv "

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']




